#!/usr/bin/env bash
set -e # halt script on error

bundle exec jekyll build --config _testconfig.yml
bundle exec htmlproof ./_site --href-ignore "#"
bundle exec scss-lint -x VendorPrefix,DuplicateProperty,SelectorDepth,NestingDepth _sass/
